services:
  stats-server:
    build: statistics
    image: docker-image-app-stats:0.1
    container_name: explore-statistics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    entrypoint:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  stats-db:
    image: postgres:16.1
    container_name: stat_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=stats
    healthcheck:
       test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
       timeout: 5s
       interval: 5s
       retries: 10
